#### IMPORTING NUMPY

In [1]:
import numpy as np

In [2]:
print(np.__all__)

['ModuleDeprecationWarning', 'VisibleDeprecationWarning', '__version__', 'show_config', 'char', 'rec', 'memmap', 'newaxis', 'ndarray', 'flatiter', 'nditer', 'nested_iters', 'ufunc', 'arange', 'array', 'asarray', 'asanyarray', 'ascontiguousarray', 'asfortranarray', 'zeros', 'count_nonzero', 'empty', 'broadcast', 'dtype', 'fromstring', 'fromfile', 'frombuffer', 'where', 'argwhere', 'copyto', 'concatenate', 'fastCopyAndTranspose', 'lexsort', 'set_numeric_ops', 'can_cast', 'promote_types', 'min_scalar_type', 'result_type', 'isfortran', 'empty_like', 'zeros_like', 'ones_like', 'correlate', 'convolve', 'inner', 'dot', 'outer', 'vdot', 'roll', 'rollaxis', 'moveaxis', 'cross', 'tensordot', 'little_endian', 'fromiter', 'array_equal', 'array_equiv', 'indices', 'fromfunction', 'isclose', 'isscalar', 'binary_repr', 'base_repr', 'ones', 'identity', 'allclose', 'compare_chararrays', 'putmask', 'flatnonzero', 'Inf', 'inf', 'infty', 'Infinity', 'nan', 'NaN', 'False_', 'True_', 'bitwise_not', 'CLIP', '

##### Creating Arrays

In [5]:
a = np.array([1, 2, 3, 4, 4, 6])
print(a)
print(type(a))

[1 2 3 4 4 6]
<class 'numpy.ndarray'>


In [9]:
myT = (1, 6, 4, 6, 4, 18)
b = np.array(myT)
print(b)
print(type(b))

[ 1  6  4  6  4 18]
<class 'numpy.ndarray'>


#### Dimension in Arrays

In [57]:
# 0-D Arrays
a = np.array(2)
print(a)
print(type(a))
print(a.ndim)
print(a.shape)

2
<class 'numpy.ndarray'>
0
()


In [54]:
# 1 - D Arrays
b = np.array([1, 2, 3, 4, 4, 6])
print(b)
print(b.ndim)
b.shape

[1 2 3 4 4 6]
1


(6,)

In [55]:
# 2 - D arrays
c = np.array([
    [1,4,7,54,5],
    [56,75,76,46,45],
    [43,56,34,56,34]
        ])
print(c)
print(c.ndim)
print(c.shape)

[[ 1  4  7 54  5]
 [56 75 76 46 45]
 [43 56 34 56 34]]
2
(3, 5)


In [56]:
# 3-D Arrays
d = np.array([
    [
        [1,4,7,54,5],
        [56,75,76,46,45],
        [348,34,5,34,56]
    ],
    [
        [2,6,7,4,7],
        [54, 75,45, 65,43],
        [34,56,45,47,56]
    ],
    [
        [34,56,65,34,565],
        [67,45,4,767,45],
        [45,57,67,45,76]
    ],
    [
        [1,4,7,54,5],
        [56,75,76,46,45],
        [348,34,5,34,56]        
    ]
])
print(d)
print(d.ndim)
print(d.shape)

[[[  1   4   7  54   5]
  [ 56  75  76  46  45]
  [348  34   5  34  56]]

 [[  2   6   7   4   7]
  [ 54  75  45  65  43]
  [ 34  56  45  47  56]]

 [[ 34  56  65  34 565]
  [ 67  45   4 767  45]
  [ 45  57  67  45  76]]

 [[  1   4   7  54   5]
  [ 56  75  76  46  45]
  [348  34   5  34  56]]]
3
(4, 3, 5)


In [32]:
# Creating Higher Dimension Arrays
f = np.array([2,4,6,23,23], ndmin=6)
print(f)

[[[[[[ 2  4  6 23 23]]]]]]


##### Array Indexing

In [34]:
b = np.array([1, 2, 3, 4, 4, 6])
print(b[-1])

6


In [35]:
d = np.array([
    [
        [1,4,7,54,5],
        [56,75,76,46,45],
        [348,34,5,34,56]
    ],
    [
        [2,6,7,4,7],
        [54, 75,45, 65,43],
        [34,56,45,47,56]
    ],
    [
        [34,56,65,34,565],
        [67,45,4,767,45],
        [45,57,67,45,76]
    ],
    [
        [1,4,7,54,5],
        [56,75,76,46,45],
        [348,34,5,34,56]        
    ]
])

In [41]:
print(d[0])
print("")
print(d[0][2])
print("")
print(d[0][2][2])

[[  1   4   7  54   5]
 [ 56  75  76  46  45]
 [348  34   5  34  56]]

[348  34   5  34  56]

5


In [43]:
print(d[2][-1][-1])
print(d[2,-1,-1])

76
76


In [44]:
print(d[1,1,2])

45


In [52]:
print(d[0:2])
print("")
print(d[0:2,0:2])
print("")
print(d[0:2,0:2,2])

[[[  1   4   7  54   5]
  [ 56  75  76  46  45]
  [348  34   5  34  56]]

 [[  2   6   7   4   7]
  [ 54  75  45  65  43]
  [ 34  56  45  47  56]]]

[[[ 1  4  7 54  5]
  [56 75 76 46 45]]

 [[ 2  6  7  4  7]
  [54 75 45 65 43]]]

[[ 7 76]
 [ 7 45]]


In [65]:
# Creating Arrays of Zeros

a = np.zeros(shape=(4,2,5))
print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [71]:
# Creating arrays of ones
import numpy as np
a = np.ones(shape=(3,4,5))
print(a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [69]:
print(a.shape)

(3,)


In [85]:
b = np.linspace(start=0, stop=100, num=30)
print(b)


[  0.           3.44827586   6.89655172  10.34482759  13.79310345
  17.24137931  20.68965517  24.13793103  27.5862069   31.03448276
  34.48275862  37.93103448  41.37931034  44.82758621  48.27586207
  51.72413793  55.17241379  58.62068966  62.06896552  65.51724138
  68.96551724  72.4137931   75.86206897  79.31034483  82.75862069
  86.20689655  89.65517241  93.10344828  96.55172414 100.        ]


In [148]:
c = np.random.randint(low=2, high=10, size=(2,3,3))
print(c)

[[[2 2 7]
  [9 3 4]
  [3 4 8]]

 [[6 7 3]
  [2 8 3]
  [3 9 6]]]


In [106]:
d = np.arange(23,60,3)
print(d)

[23 26 29 32 35 38 41 44 47 50 53 56 59]


In [137]:
# Shape of an array

In [138]:
print(f.shape)

(6, 4)


In [130]:
f = np.full(shape=(6,4), fill_value=["Hi", "Hello", "dad", 3])
print(f)

[['Hi' 'Hello' 'dad' '3']
 ['Hi' 'Hello' 'dad' '3']
 ['Hi' 'Hello' 'dad' '3']
 ['Hi' 'Hello' 'dad' '3']
 ['Hi' 'Hello' 'dad' '3']
 ['Hi' 'Hello' 'dad' '3']]


In [161]:
b = f.reshape((8,3), order="c")
print(b)
print(b.shape)

[['Hi' 'Hello' 'dad']
 ['3' 'Hi' 'Hello']
 ['dad' '3' 'Hi']
 ['Hello' 'dad' '3']
 ['Hi' 'Hello' 'dad']
 ['3' 'Hi' 'Hello']
 ['dad' '3' 'Hi']
 ['Hello' 'dad' '3']]
(8, 3)


In [160]:
help(f.reshape)

Help on built-in function reshape:

reshape(...) method of numpy.ndarray instance
    a.reshape(shape, order='C')
    
    Returns an array containing the same data with a new shape.
    
    Refer to `numpy.reshape` for full documentation.
    
    See Also
    --------
    numpy.reshape : equivalent function
    
    Notes
    -----
    Unlike the free function `numpy.reshape`, this method on `ndarray` allows
    the elements of the shape parameter to be passed in as separate arguments.
    For example, ``a.reshape(10, 11)`` is equivalent to
    ``a.reshape((10, 11))``.



In [136]:
b = np.matrix([[2,4,5,7,36],[4,6,8,5,4]])
print(b)
print(b.ndim)
print(type(b))

[[ 2  4  5  7 36]
 [ 4  6  8  5  4]]
2
<class 'numpy.matrix'>


In [169]:
import numpy as np
b = np.arange(1,61)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]


In [171]:
c = b.reshape((4,5,3), order="c")
print(c)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]]

 [[31 32 33]
  [34 35 36]
  [37 38 39]
  [40 41 42]
  [43 44 45]]

 [[46 47 48]
  [49 50 51]
  [52 53 54]
  [55 56 57]
  [58 59 60]]]


In [179]:
d = c.sum(axis=0)
print(d)

[[ 94  98 102]
 [106 110 114]
 [118 122 126]
 [130 134 138]
 [142 146 150]]


In [182]:
d.reshape((15,), order="f")

array([ 94, 106, 118, 130, 142,  98, 110, 122, 134, 146, 102, 114, 126,
       138, 150])

In [184]:
f = c.reshape((3,4,5))
print(f)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [186]:
g = f.reshape((12,5))
print(g)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]


In [195]:
p = np.arange(20,32).reshape((4,3))
z = np.arange(100,112).reshape((4,3))

print(p)
print("")
print(z)

[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]]

[[100 101 102]
 [103 104 105]
 [106 107 108]
 [109 110 111]]


In [197]:
adder = p + z
print(adder)

[[120 122 124]
 [126 128 130]
 [132 134 136]
 [138 140 142]]


In [198]:
multi = p * z
print(multi)

[[2000 2121 2244]
 [2369 2496 2625]
 [2756 2889 3024]
 [3161 3300 3441]]


In [199]:
divider = p / z
print(divider)

[[0.2        0.20792079 0.21568627]
 [0.22330097 0.23076923 0.23809524]
 [0.24528302 0.25233645 0.25925926]
 [0.26605505 0.27272727 0.27927928]]


In [203]:
minus = z - p
print(minus)

[[80 80 80]
 [80 80 80]
 [80 80 80]
 [80 80 80]]


In [206]:
divider2 = p**2
print(divider2)

[[400 441 484]
 [529 576 625]
 [676 729 784]
 [841 900 961]]


In [174]:
help(c.sum)

Help on built-in function sum:

sum(...) method of numpy.ndarray instance
    a.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)
    
    Return the sum of the array elements over the given axis.
    
    Refer to `numpy.sum` for full documentation.
    
    See Also
    --------
    numpy.sum : equivalent function



##### Searching Arrays

In [3]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 4, 4])
print(a)

[1 2 3 4 5 4 4]


In [11]:
aa = np.where(a > 3)
print(aa)

(array([3, 4, 5, 6], dtype=int64),)


In [9]:
print(a[aa])

[4 5 4 4]


##### Using any( ) and all( ) function

In [15]:
a = np.array([1, 2, 3, 4, 5, 4, 4])

b = np.all(a>3)
c = np.any(a==3)

print(b)
print(c)

False
True


##### Sorting Arrays

In [20]:
fruits = np.array(["Mango", 'Orange', 'Banana', 'Apple', 'Guava', 'Pear', 'Watermelon'])
print(fruits)

['Mango' 'Orange' 'Banana' 'Apple' 'Guava' 'Pear' 'Watermelon']


In [23]:
print(np.sort(fruits))
b = np.sort(fruits)
print(b)

['Apple' 'Banana' 'Guava' 'Mango' 'Orange' 'Pear' 'Watermelon']
['Apple' 'Banana' 'Guava' 'Mango' 'Orange' 'Pear' 'Watermelon']


In [24]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(arr)

[[3 2 4]
 [5 0 1]]


In [28]:
print(np.sort(arr, axis=0))

[[3 0 1]
 [5 2 4]]


In [29]:
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


##### Filtering Array

In [82]:
import numpy as np
arr = np.array([41, 42, 43, 44])

ind = [True, False, False, True]

In [83]:
print(arr[ind])

[41 44]


In [84]:
# Creating a filter that will return only values
# less than 20

a = np.array([19, 41, 42, 12, 43, 9, 44, 25, 3, 6])

In [52]:
# Method 1: where ( ) function
aa = np.where(arr < 20)
print(aa)

print(arr[aa])

(array([0, 3, 5, 8, 9], dtype=int64),)
[19 12  9  3  6]


In [58]:
# Method 2: Boolean Indexing
print(arr)
aa = arr < 20
print(aa)

print(arr[aa])

[19 41 42 12 43  9 44 25  3  6]
[ True False False  True False  True False False  True  True]
[19 12  9  3  6]


In [61]:
# Method 3: Using the loops 
print(arr)

#Creating an empty list
index = []

# Go through each element in the array
for x in arr:
    if x < 20:
        index.append(True)
    else:
        index.append(False)

print(index)
print(arr[index])

[19 41 42 12 43  9 44 25  3  6]
[True, False, False, True, False, True, False, False, True, True]
[19 12  9  3  6]


#### Ufuncs

In [62]:
a = np.array([2,4,5])
b = np.array([4,3,7])

c = a + b
print(c)

[ 6  7 12]


In [63]:
a = [2,4,5]
b = [4,3,7]
c = a + b
print(c)

[2, 4, 5, 4, 3, 7]


##### Addition

In [65]:
c = np.add(a, b)
print(c)

[ 6  7 12]


In [70]:
# Subtraction
print(a)
print(b)
print("")
c = np.subtract(a,b)
print(c)

[2, 4, 5]
[4, 3, 7]

[-2  1 -2]


In [71]:
# Multiplication
print(a)
print(b)
print("")
c = np.multiply(a,b)
print(c)

[2, 4, 5]
[4, 3, 7]

[ 8 12 35]


In [72]:
# Division
print(a)
print(b)
print("")
c = np.divide(a,b)
print(c)

[2, 4, 5]
[4, 3, 7]

[0.5        1.33333333 0.71428571]


In [73]:
# Exponentiation
print(a)
print(b)
print("")
c = np.power(a,b)
print(c)

[2, 4, 5]
[4, 3, 7]

[   16    64 78125]


In [75]:
# Remainder
print(a)
print(b)
print("")
c = np.mod(a,b)
c = np.remainder(a,b)
print(c)

[2, 4, 5]
[4, 3, 7]

[2 1 5]


In [76]:
# Quotient and Mod
print(a)
print(b)
print("")
c = np.divmod(a,b)
print(c)

[2, 4, 5]
[4, 3, 7]

(array([0, 1, 0], dtype=int32), array([2, 1, 5], dtype=int32))


In [77]:
# Absolute Values
arr = np.array([-1, -2, 1, 2, 3, -4])
c = np.absolute(arr)
print(c)

[1 2 1 2 3 4]


#### Rounding Decimals

In [100]:
# Truncate
import numpy as np
a = np.linspace(2,9,7)
print(a)

[2.         3.16666667 4.33333333 5.5        6.66666667 7.83333333
 9.        ]


In [101]:
print(np.trunc(a))

[2. 3. 4. 5. 6. 7. 9.]


In [108]:
# Using around( )
b = np.around(a, 2)
print(b)

[2.   3.17 4.33 5.5  6.67 7.83 9.  ]


In [110]:
# Floor and Ceil
aa = np.array([7.69, -4.46])

In [111]:
f = np.floor(aa)
c = np.ceil(aa)

print(f)
print(c)

[ 7. -5.]
[ 8. -4.]


In [118]:
# Logarithms
# Base 2
aa = np.array([7.69, 4.46])
print(np.log2(aa))

# Base 10
print(np.log10(aa))
print(np.around(np.log10(aa),4))
print(np.log(aa))

[2.9429836  2.15704371]
[0.88592634 0.64933486]
[0.8859 0.6493]
[2.03992078 1.49514877]


In [122]:
# Addition and Summation
a = np.arange(1,5)
b = np.arange(8,12)
print(a)
print(b)


[1 2 3 4]
[ 8  9 10 11]


In [123]:
# Add
c = np.add(a, b)
print(c)

[ 9 11 13 15]


In [125]:
# Sum
c = np.sum([a, b])
print(c)

48


In [132]:
# Summing along an axis
c = np.sum([a, b], axis=1)
print(c)

[10 38]


In [133]:
# Cummulative sum
print(a)
print(np.cumsum(a))

[1 2 3 4]
[ 1  3  6 10]


In [134]:
# Product
a = np.arange(1,7)
b = np.prod(a)
print(a)
print(b)

[1 2 3 4 5 6]
720


In [138]:
a = np.arange(1,5)
b = np.arange(8,12)

c = np.prod([a,b])
print(a)
print(b)
print(c)

[1 2 3 4]
[ 8  9 10 11]
190080


In [141]:
# Multiplying along an axis
a = np.arange(1,5)
b = np.arange(8,12)

c = np.prod([a,b], axis=1)
print(a)
print(b)
print(c)

[1 2 3 4]
[ 8  9 10 11]
[  24 7920]


In [145]:
# Cummulative Product
b = np.arange(8,12)
c = np.cumprod(b)
print(b)
print(c)

[ 8  9 10 11]
[   8   72  720 7920]


In [153]:
# Differences
a = np.array([10, 15, 25, 5, 6, 10, 12])

b = np.diff(a)
c = np.diff(a, n=2)
d = np.diff(a, n=3)
print(a)
print(b)
print(c)
print(d)

[10 15 25  5  6 10 12]
[  5  10 -20   1   4   2]
[  5 -30  21   3  -2]
[-35  51 -18  -5]


In [155]:
a = np.array([10, 15, 25, 5, 6, 10, 12])
b = np.array([23, 15, 88, 5, 27, 90, 12])
c = np.diff([a,b])
print(c)

[[  5  10 -20   1   4   2]
 [ -8  73 -83  22  63 -78]]


##### LCM (Lowest Common Multiple)

In [157]:
a = 18
b = 24

c = np.lcm(a,b)
print(c)

72


In [160]:
# Finding the LCM of an array or list
c = np.lcm.reduce([12, 25, 10])
print(c)

300


##### GCD (Greatest Common Divisor)

In [161]:
a = 18
b = 24

c = np.gcd(a,b)
print(c)

6


In [164]:
# Finding the GCD of an array or list
c = np.gcd.reduce([12, 24, 36])
print(c)

12


##### Trigonometric Function

In [165]:
np.pi

3.141592653589793

In [166]:
a  = 60
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))


-0.3048106211022167
-0.9524129804151563
0.320040389379563


### Set Operations

In [167]:
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

b = np.unique(arr)
print(b)

[1 2 3 4 5 6 7]


In [168]:
# Finding Union and Intersection of a set
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

c = np.union1d(a,b)
print(c)

[1 2 3 4 5 6]


In [169]:
# Finding Union and Intersection of a set
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

c = np.intersect1d(a,b)
print(c)

[3 4]


In [172]:
#Set difference
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

c = np.setdiff1d(a,b)
print(c)

# Returning the difference in "b"
d = np.setdiff1d(b,a)
print(d)

[1 2]
[5 6]


In [173]:
# Finding symmetric difference
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

c = np.setxor1d(a,b)
print(c)

[1 2 5 6]
