# WHAT IS NUMPY?

Numpy is the core library for scientific computing in Python.
It provides a high-performance multidimensional array object, and tools for working with these array

### Application of Numpy
-Image Processing 

-Signal Processing

-Linear algebra



In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = np.array([(1,2,3),(4,5,6)])

In [ ]:
print(a)

In [ ]:
print(b)

# Advantage of Numpy over List

It occupies less memory.
It is fast. 
It is more convenient.


# A Multidimensional Array Object

Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalentoperations between scalar elements:

## Creating ndarrays

In [ ]:
data1 = [6, 5, 7, 3, 3.6]

In [ ]:
arr1 = np.array(data1)

In [ ]:
arr1

In [20]:
data2 = [[1,2,3,1],[4,2,7,6]]
arr2 = np.array(data2)

In [ ]:
#Specifying the data type
arr4 = np.array(data2, dtype=np.float64)
arr4

In [ ]:
arr4.dtype


In [ ]:
#Item size
arr4.itemsize

In [ ]:
arr2

In [ ]:
#Printing the dimension
arr2.ndim

In [ ]:
#Printing the size of an array
arr2.size

In [ ]:
#Printing the shape
arr2.shape

#### You can Reshape an array
It is just like transposing the array, but I think there is a difference.

When reshaping arrays, the size must be consistent with the original.

In [ ]:
arr2

In [ ]:
res = arr2.reshape(4,2)
res

In [ ]:
#This case, the second condition is determined automatically
res = arr2.reshape(4,-1)
res

In [ ]:
res = arr2.reshape(8,1)
res

In [ ]:
#Transpose of an array
# (2,3,4,5) becomes (5,4,3,2)
res = arr2.T
res

In [ ]:
#Data type used
arr2.dtype

In [ ]:
arr1.dtype

In [24]:
foo = np.random.randint(low=1, high=6, size=(8))
foo

array([4, 3, 1, 3, 4, 5, 5, 2])

In [ ]:
# Row major order
# orders the row axis first
foo.reshape((4,2), order='C')

In [ ]:
# Row major order
# orders the row axis first
foo.reshape((2,2,2), order='C')

In [ ]:
# Column major order
#Orders the last axis (column) first
foo.reshape((4,2), order='F')

In [ ]:
# Column major order
#Orders the last axis (column) first
foo.reshape((2,2,2), order='F')

In [ ]:
foo.shape = (4,2)
foo

In [ ]:
foo.T
# or
np.transpose(foo)

In [27]:
#With starting point and steps
np.arange(5,12,0.3)

array([ 5. ,  5.3,  5.6,  5.9,  6.2,  6.5,  6.8,  7.1,  7.4,  7.7,  8. ,
        8.3,  8.6,  8.9,  9.2,  9.5,  9.8, 10.1, 10.4, 10.7, 11. , 11.3,
       11.6, 11.9])

### SLICING

In [ ]:
arr2

In [ ]:
# Selecting the 3rd element in the second row
arr2[1,2]


### Splitting Arrays
It takes two arguments, the array to be splitted and the number of splits

In [ ]:
arr2

In [ ]:
np.hsplit(arr2,4)

In [ ]:
#Indexing the splitted array
np.hsplit(arr2,4)[1][1][0]

In [ ]:
np.vsplit(arr2,2)

#### linspace function prints equidistant numbers between two range

In [8]:
#Specifies the range and the number of elements
#The default space is 50
new = np.linspace(1,2,8)
new

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        ])

In [ ]:
np.linspace(start=0, stop=10, num = 8)

In [ ]:
np.linspace(start=[0,5,6], stop=[10,15,7], num = 10)

In [ ]:
np.linspace(start=[0,5,6], stop=[10,15,7], num = 10, axis=1)

#### Printing sum, max, min

In [ ]:
#Returns the maximum number
arr2.max()

In [ ]:
#Returns the minimum number
arr2.min()

In [ ]:
#Returns the sum of the array
arr2.sum()

#### The rows are called axis1 and the columns are called axis 0
You can find the sum of the variious axes

In [ ]:
arr2.sum(axis=0)

In [ ]:
arr2.sum(axis=1)

In [ ]:
arr2

In [ ]:
#Finding the square root 
np.sqrt(arr2)

In [ ]:
#Finding the standard deviation
np.std(arr2)

## BASIC ARITHMETIC OPERATIONS
These operations are done element wise.

In [32]:
#Example
a =np.array([[1,5,7],[4,7,9]])
b =np.array([[5,9,1],[4.3,8,3]])


In [27]:
c =np.array([[5,9],[4.3,8],[33,6]])

In [ ]:
a

In [ ]:
b


In [ ]:
c


In [33]:
c.itemsize
b.itemsize

8

In [ ]:
#ADDITION
a+b

In [25]:
dd = np.full(shape=(2,3), fill_value=6)
dd
a + dd

ValueError: operands could not be broadcast together with shapes (8,) (2,3) 

In [ ]:
#SUBTRACTION
a-b

In [ ]:
#MULTIPLICATION
a*b

In [ ]:
#Matrix multiplication
a @ c

In [ ]:
#DIVISION
a/b

#### Vertical Stacking and Horizontal Stacking.

In [ ]:
## Vertical stacking
np.vstack((a,b))

In [ ]:
## Horizontal stacking
np.hstack((a,b))

In [ ]:
#Converting ndarray to one dimension
a.ravel()

## SPECIAL FUNCTIONS

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x = np.arange(0,3*np.pi, 0.1)

In [ ]:
x


In [ ]:
y= np.sin(x)

In [ ]:
y = np.cos(x)

In [ ]:
y = np.tan(x)

In [ ]:
y


In [ ]:
plt.plot(x,y)

In [ ]:
plt.show()

### Exponential and Logarithmic Function

In [ ]:
arr2

In [ ]:
ar = np.exp(arr2)
ar

In [ ]:
#Finding the natural logarithm
ar = np.log(arr2)
ar

In [ ]:
#Finding the logarithm to base 10
ar = np.log10(arr2)
ar

In [ ]:
##25/08/2023

 Every element in the array must be of the same type and size.

If an array's elements are also arrays, those inner arrays must have the same type and number of elements as each other.

In [ ]:
np.zeros(shape=(3,5))

In [40]:
##Making use of the fill value
np.full(shape=(3,5), fill_value="dog")

array([['dog', 'dog', 'dog', 'dog', 'dog'],
       ['dog', 'dog', 'dog', 'dog', 'dog'],
       ['dog', 'dog', 'dog', 'dog', 'dog']], dtype='<U3')

In [39]:
np.arange(start=1, stop=10, step=2)

array([1, 3, 5, 7, 9])

#### Slicing operation
Syntax: foo[Start index : end index : Step size]

In [38]:
np.random.randint(low=1, high=90, size=(3,2,5))

array([[[19, 48, 22, 70, 34],
        [52, 61,  1, 39, 32]],

       [[85, 23, 11, 13, 89],
        [58, 63, 40, 52, 65]],

       [[ 5, 48,  5, 57, 84],
        [ 6, 62, 83, 18, 12]]])

In [43]:
foo = np.random.randint(low=1, high=90, size=(8))

In [ ]:
foo

In [ ]:
#Prints from the begining to the fourth element
foo[:4]

In [ ]:
#Prints from the fifth element to the end
foo[4:]

In [44]:
#Prints from the begining to the end skipping with steps
foo[::3]

array([89, 70, 86])

In [ ]:
#we can modify multiple element at once
# However the shape must be same
foo[::3] = [100,200,300]

In [ ]:
foo

In [ ]:
##For the last element
foo[-1]
foo[len(foo)-1]

In [ ]:
##You can pass in a list
foo[[1,2,1,-1]]

In [ ]:
##the inner expression produces a list of zeros
##Which is used as the index
foo[np.zeros(shape=3, dtype='int32')]

#### Working with 2-D Arrays

In [ ]:
bar = np.array(
    [
        [5,10,15,20],
        [25,30,35,40],
        [45,50,55,60]
    ]
)

In [ ]:
bar

In [ ]:
#Entire row
bar[0]

In [ ]:
#single row as a 2-d array
bar[1,None]

In [ ]:
bar[-1]

In [ ]:
bar[:2]

In [ ]:
#comma can be used to swparate row index from the column index
bar[1:3,[-2,-1]]

In [ ]:
#same thing
bar[0,0]
bar[0][0]

In [ ]:
#replacing values
bar[0,0] = -1
bar

In [ ]:
#replacing one row with the other
bar[1] = bar[2]
bar

In [ ]:
#Printing zeros across the diagnal
bar[np.arange(3),np.arange(3)] = np.zeros(3, 'int32')
bar

#bar[[0,1,2],[0,1,2]] = [0,0,0]

In [ ]:
np.zeros(3, 'int32')

ONE DIMENSIONAL ARRAY --> ROW

TWO DIMENSIONAL ARRAY --> MATRIX

THREE DIMENSIONAL ARRAY --> ROW OF MATRICES

FOUR DIMENSIONAL ARRAY --> MATRIX OF MATRICES

In [ ]:
#Creating a three dimensional array
zoo =  np.array([
    [
        [10,20],
        [30,40],
        [50,60]
    ],
    [
        [11,12],
        [13,14],
        [15,16]
    ],
])
zoo

In [ ]:
##Replacing 1 matrix, every row, of the 2 column with a number
zoo[0,:,1] = 5
zoo


### Challenge 1
#### Setup
With your high school reunion fast approaching, you decide to get in shape and lose some weight. You record your weight every day for five weeks on a Monday. Given these daily weights, build an array with your average weight per weekend


In [ ]:
dailywts = 185 - np.arange(5*7)/5
dailywts


In [ ]:
np.arange(5*7)/5

In [ ]:
np.arange(35)/5

#### Solution

In [ ]:
##Getting Friday and Saturday
dailywts[5::7]

In [ ]:
#Saturday
dailywts[6::7]

In [ ]:
#Adding the two arrays element wise
dailywts[5::7] + dailywts[6::7]

In [ ]:
#Getting the average by division
(dailywts[5::7] + dailywts[6::7])/2

### Challenge 2
#### Setup
After binge watching the discovery channel, you dich your job as a trial lawyer to become a gold miner. You decide to prospect five locations underneath a 7*7 grid of land. How much gold to you uncover at each location?


In [ ]:
np.random.seed(5555)
gold = np.random.randint(0,10,(7,7))
## gold = np.random.randint(low=0,high=10,size=(7,7))
gold

In [ ]:
locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])
locs

#### Solution

In [ ]:
gold[0,4]

In [ ]:
gold[2,2]

In [ ]:
#Passing a list of row indices and column indices
gold[[0,2],[4,2]]

In [ ]:
#getting entire row and column indices
locs[:, 0]

In [ ]:
locs[:,1]

In [ ]:
gold[locs[:, 0],locs[:,1]]

### Broadcasting 
Suppose we want to add two arrays, A and B...

Moving Backwards from the last dimension of each array, we check if their dimensions are compatible.

Dimensions are compatible if they are equal or either of them is one.

If all of A's dimension are compatible with B's dimensions, or vice versa, they are compatible arrays.

In [ ]:
#Examples
np.random.seed(1234)
A = np.random.randint(low=1, high=10, size = (3,4))
B = np.random.randint(low=1, high=10, size = (3,1))


In [ ]:
A

In [ ]:
B

In [ ]:
A+B

In [ ]:
np.random.seed(1234)
A = np.random.randint(low=1, high=10, size = (4,4))
B = np.random.randint(low=1, high=10, size = (2,1))


In [ ]:
A + B

In [ ]:
np.random.seed(1234)
A = np.random.randint(low=1, high=10, size = (3,1,4))
B = np.random.randint(low=1, high=10, size = (2,1))


In [ ]:
A

In [ ]:
B

In [ ]:
A+B

In [ ]:
##Making use of the newaxis
#Creates a new axis either in front or behind, depending on where the functtion
# is placed. It converts a 1-d array to 2,3...d array.

In [ ]:
#Example
aa = np.array([3, 11, 4, 5])
bb = np.array([5, 0, 3])

In [ ]:
aa


In [ ]:
bb

In [ ]:
#More of a transpose
aa[:, np.newaxis]

In [ ]:
bb[np.newaxis,:]

In [ ]:
##Newaxis is an alias for the 'None' keyword
bb[None,:]

### Boolean Indexing

In [ ]:
import numpy as np

In [ ]:
np.random.seed(1234)
foo = np.random.randint(1,9,(3,3))
foo

In [ ]:
#Gives an array of boolean values
foo == 5

In [ ]:
foo < 5

In [ ]:
foo > 5

In [ ]:
foo <= 5

In [ ]:
foo >= 5

In [ ]:
(foo == 5) | (foo != 5)

In [ ]:
(foo == 5) & (foo != 5)

In [ ]:
foo != 5

In [ ]:
mask = foo != 5

In [ ]:
foo

In [ ]:
foo[mask]

In [ ]:
#We can set all the values that corresponds to True to zero or any number
foo[mask] = 100
foo

#### Using a 1-D boolean array to pick rows from a 2-D array

In [ ]:
#You can use a 1-D boolean array to pick rows from a 2-D array
rows_1_and_3 = np.array([True, False, True])
cols_2_and_3 = np.array([False, True, True])

In [ ]:
#It since the array is a 1-D array, it pick the first and the third row
foo[rows_1_and_3] #like foo[[0,2]]

In [ ]:
 foo[[0,2]]

In [ ]:
#It since the array is a 1-D array, it pick the second and the third row
foo[cols_2_and_3] #like foo[:, [1,2]]

In [ ]:
# Selecting all the rows, then the column number that corresponds to True in
# boolean array
foo[:, rows_2_and_3]

In [ ]:
foo[:, [1,2]]

In [ ]:
foo[rows_1_and_3, cols_2_and_3] #like foo[[0,2],[1,2]]

In [ ]:
# Here we have lists of pairs of row indices and column indices
foo[[0,2],[1,2]] 

#### Examples of Boolean indexing in action

In [ ]:
import numpy as np

In [ ]:
names = np.array(["Dennis", "Lucius", "Mike", "Frank", "Bae"])
ages = np.array([43, 44, 43, 42, 74])
genders =np.array(['male', 'female', 'male', 'male', 'female'])

In [ ]:
#Who's at least 44?
ages >= 44

In [ ]:
names[ages >= 44]

In [ ]:
#Which males are over 42?
genders == 'male'

In [ ]:
ages > 42

In [ ]:
(genders == 'male') & (ages > 42)

In [ ]:
names[(genders == 'male') & (ages > 42)]

In [ ]:
#And who's not a male or is younger than 43?
~(genders == 'male') | (ages < 43)

In [ ]:
names[~(genders == 'male') | (ages < 43)]

### nan
Use to represent missing or invalid values

In [ ]:
bot = np.ones(shape=(3,4))
bot[[0,2],[1,2]] = np.nan
bot

In [ ]:
## you may want to identify which element are nan,
# but the result will surprise you
bot == np.nan

In [ ]:
np.nan == np.nan

In [ ]:
#Equivalence between missing or invalid values is not well defined
np.nan != np.nan

In [ ]:
#you can use this function to check which element is nan
np.isnan(bot)

In [ ]:
#nan is a special floating point constant, it can only exist in an arrya of
#floats
doo = np.array([1,2,1,5], dtype='int32')
doo[:2] = np.nan

#### Infinite Values in Numpy

In [ ]:
import numpy as np

In [ ]:
np.array([np.inf, np.NINF])

In [ ]:
#These value occur when you divide by zero
np.array([1, -1])/0

In [ ]:
np.inf * 2 

In [ ]:
np.inf + np.inf

In [ ]:
np.inf - np.inf

In [ ]:
np.inf / np.inf

In [ ]:
np.inf == np.inf

In [ ]:
np.NINF == np.NINF

In [ ]:
coo = np.array([2, 4, np.inf, 8, np.NINF])

In [ ]:
coo == np.NINF

In [ ]:
coo == np.inf

In [ ]:
np.isposinf(coo)

In [ ]:
np.isneginf(coo)

In [ ]:
np.isinf(coo)

#### Random Values in Numpy

In [ ]:
import numpy as np

In [ ]:
#Getting reproducable result
np.random.seed(1111)
np.random.randint(low=1, high=7, size=3)

In [ ]:
##Drawing values without replacement
np.random.seed(22357)
np.random.choice(
    a = np.arange(1,7), #this is the choice of list
    size = 3,
    replace = False,
    p = None
)

In [ ]:
##Creating samples with different probabilites
## 'p' should have the same number of element as 
##the array of values
## sum of the probability should be equal to one
##Drawing values without replacement

np.random.choice(
    a = np.arange(1,7), #this is the choice of list
    size = 3,
    replace = False, 
    p = np.array([0.1,0.1,0.1,0.1,0.3,0.3])
)

In [ ]:
## Sampling strins without replacement
np.random.choice(
    a = np.array(['you', 'can', 'use', 'strings','too']),
    size = 3, 
    replace = False,
    p = None
)

In [ ]:
##Sampling rows from a 2-D array
soo = np.arange(1,11)
soo

In [ ]:
soo = soo.reshape((5,-1), order = 'C')
soo

In [ ]:
soo.shape[0]

In [ ]:
##Sampling 3 rows with replacement
np.random.seed()
rand_rows = np.random.randint(
    low = 0,
    high = soo.shape[0],
    size = 3
)
rand_rows

In [ ]:
soo[rand_rows]

In [ ]:
#Sampling without replacement
np.random.seed(1234)
rand_rows = np.random.choice(
    a = np.arange(start=0, stop=soo.shape[0]),
    replace = False,
    size = 3
)
print(rand_rows)

In [ ]:
#Subsetting soo
soo[rand_rows]

In [ ]:
soo


In [ ]:
##it only shuffles the data along its first axis
#only the rows
np.random.permutation(soo)

In [ ]:
##uniform distribution
np.random.uniform(low=1.0, high=3.0, size=(2,2))

In [ ]:
#Normal distribution
#here 'loc'= mean, 'scale' = stdev, 'size' = tuple
np.random.normal(loc=0.0, scale=1.0, size=(2,3))

In [ ]:
#Binomial distribution
np.random.binomial(n = 60, p = 0.25, size = (4,2))

##### Creating a Customized Random Generator

In [ ]:
#Create a generator
generator = np.random.default_rng(seed=123)

In [ ]:
#Sampling three ints between 1 and 6 with replacement
#np.random.randint(low=1, high=7, size=3)
generator.integers(low=1, high=7, size=3)

In [ ]:
#Sampling three ints between 1 and 8 without replacement
#np.random.choice(a=9, size=3, replace=True)
generator.choice(a=9, size=3, replace=True)

In [ ]:
soo

In [ ]:
#Randomly shuffling the rows of a 2d array, soo
#np.random.permutation(foo)

generator.permutation(soo, axis=1)

In [ ]:
#Randomly sampling values from a uniform distribution
#np.random.uniform(low=1.0, high=2.0, size=(2,2))
generator.uniform(low=1.0, high=2.0, size=(2,2))

In [ ]:
#Randomly sampling values from a standard normal distribution
#np.random.normal(loc=0.0, scale=1.0, size=2)
generator.normal(loc=0.0, scale=1.0, size=3)

### Challenge 3
You're a relationship scientist and you've developed a questionaire that determines a person's love score, a real-valued number between 0 and 100. Your theory is that two people with similar love score should make a good match. Given the love scores for 10 different people, create a matrix where (i,j) give the absolute difference of the love scores for person i and person j.

In [ ]:
import numpy as np

In [ ]:
generator = np.random.default_rng(1010)
love_scores = np.round(generator.uniform(low=0, high=100, size=10), 2)
love_scores

#### Solution

In [ ]:
np.set_printoptions(linewidth=999)
#don't wrap print until 999 characters

In [ ]:
a = love_scores[:,None]
a

In [ ]:
b = love_scores[None, :]
b

In [ ]:
np.set_printoptions(linewidth=999)
a - b

In [ ]:
np.set_printoptions(linewidth=999)
abs(a - b)

### Challenge 4
You're a vindictive, hate professor and one of your pet peeves is when students rush through their exams. To teach them a lesson, you decide to give 0s to the first three students who score less than sixty, in the order they turned in their exams. So, given a 1d array of integers, identify the first three values less than sixty and replace them with zero


In [ ]:
import numpy as np

In [ ]:
genrator = np.random.default_rng(80085)
score = np.round(generator.uniform(low=30, high=100, size=15))
score

#### Solution

In [ ]:
score < 60

In [ ]:
(score<60).nonzero()

In [ ]:
(score<60).nonzero()[0]

In [ ]:
(score<60).nonzero()[0][:3]

In [ ]:
score[(score<60).nonzero()[0][:3]]=0
score

# NUMPY INTRODUCTION

### What is NumPy?
NumPy is a python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

### Why Use NumPy ?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster that traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

### Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

### Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

### Where is the NumPy Codebase?
The source code for NumPy is located at this github repository https://github.com/numpy/numpy

In [1]:
import numpy as np

In [ ]:
print(np.__all__)

In [ ]:
import random as rd

In [ ]:
help(rd.randint)

In [2]:
import numpy as np

In [ ]:
help(np.array)

In [2]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [4]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
print(arr[1,-1])

10


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [4]:
arr1 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    
    [
        [7,8,9],
        [10,11,12]
    ],
    
    [
        [47,48,73],
        [35,92,-23]
    ]
])

In [5]:
print(arr1.nonzero())

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], dtype=int64), array([0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))


### Creating a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4, 6])
print(arr)
print(type(arr))

[1 2 3 4 6]
<class 'numpy.ndarray'>


In [9]:
# Using tuple to create arrays
import numpy as np
arr = np.array((1, 2, 3, 4, 6))
print(arr)

[1 2 3 4 6]


#### 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [11]:
import numpy as np
arr = np.array(48)
print(arr)

48


#### 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4, 6])
print(arr)

[1 2 3 4 6]


#### 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [17]:
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,7]
])

print(arr)

[[1 2 3]
 [4 5 7]]


#### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [18]:
import numpy as np
arr = np.array([
    [
        [2,3,4],
        [6,8,4]
    ],
    
    [
        [1,8,4],
        [6,9,2]
    ]
])

print(arr)

[[[2 3 4]
  [6 8 4]]

 [[1 8 4]
  [6 9 2]]]


#### Checking Number of Dimensions
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [19]:
a = np.array(48)
b = np.array([1, 2, 3, 4, 6])

c = np.array([
    [1,2,3],
    [4,5,7]
])

d = np.array([
    [
        [2,3,4],
        [6,8,4]
    ],
    
    [
        [1,8,4],
        [6,9,2]
    ]
])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


#### Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [21]:
import numpy as np
c = np.array([
    [1,2,3],
    [4,5,7]
], ndmin=5)

print(c)
print(c.ndim)

[[[[[1 2 3]
    [4 5 7]]]]]
5


In [23]:
#Printing the size of an array
c.size

6

In [22]:
#Printing the shape
c.shape

(1, 1, 1, 2, 3)

##### Creating Arrays Using Various Methods

There are other number of functions for creating new arrays
##### i. Zeros Function

In [9]:
#The zeros function
#Creates a one dimensional array with the number of zeros specified
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
#Two dimensional zeros 
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
#Three dimensional zeros 
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

##### ii. Ones Function

In [17]:
# Ones method
np.ones(5, dtype=np.int8)

array([1, 1, 1, 1, 1], dtype=int8)

In [12]:
#Two dimensional ones
np.ones((3,4), dtype=np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

##### iii. Empty function

#### empty creates an array without initializing its values to any particular value
We pass in a tuple to determine its shape

In [23]:
### Using the 'empty' function
np.empty((3,4))

array([[1.31999105e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.08221785e-312, 1.22286436e+161, 6.01788585e-067,
        1.70388597e-051],
       [7.25911189e-043, 8.98210395e-067, 2.89817785e-057,
        4.27406336e-033]])

##### iv The Arange Function
arange is an array-valued version of the built-in python range function.

In [25]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
#With starting point
import numpy as np
np.arange(5,13)
a.reshape(4,2)

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

##### v. The Eye function
It creates a unit matrix (diagonal matrix) of one

Syntax: eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

In [48]:
import numpy as np
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
#Shifting the diagonal position
import numpy as np
d = np.eye(4, k=-1)
print(d)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [56]:
# Specifying the number of column
import numpy as np
e = np.eye(3, M=5, k=2)
print(e)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [66]:
# Specifying the data type
import numpy as np
e = np.eye(3, M=5, k=2, dtype="bool")
print(e)

[[False False  True False False]
 [False False False  True False]
 [False False False False  True]]


##### vi. The identity function
The identity array is a square array with ones on the main diagonal.


Syntax: identity(n, dtype=None, *, like=None)

In [63]:
# Example
import numpy as np
np.identity(5, dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [64]:
# Example
import numpy as np
np.identity(5, dtype="str")

array([['1', '', '', '', ''],
       ['', '1', '', '', ''],
       ['', '', '1', '', ''],
       ['', '', '', '1', ''],
       ['', '', '', '', '1']], dtype='<U1')

In [65]:
# Example
import numpy as np
np.identity(5, dtype="bool")

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

##### vii. The full function
 Return a new array of given shape and type, filled with `fill_value'
 
 Syntax: full(shape, fill_value, dtype=None, order='C', *, like=None)

In [70]:
##Making use of the fill value
import numpy as np
np.full(shape=(3,5), fill_value="dog")

array([['dog', 'dog', 'dog', 'dog', 'dog'],
       ['dog', 'dog', 'dog', 'dog', 'dog'],
       ['dog', 'dog', 'dog', 'dog', 'dog']], dtype='<U3')

In [74]:
## The fill value can be inform of an array and
# should be equal to the number of column of the array
import numpy as np
np.full(shape=(3,5), fill_value=["dog", "cow", "rat", 'cat', 'hen'])

array([['dog', 'cow', 'rat', 'cat', 'hen'],
       ['dog', 'cow', 'rat', 'cat', 'hen'],
       ['dog', 'cow', 'rat', 'cat', 'hen']], dtype='<U3')

#### Accessing Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [34]:
# Example 
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[3])

4


In [29]:
print(arr[3] + arr[2])

7


##### Accessing 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

In [31]:
import numpy as np
arr = np.array([
    [1,2,3,4,5],
    [7,5,9,4,8]
])

print(arr[1][2])
print(arr[1,4])

9
8


3-D Arrays

In [83]:
import numpy as np
d = np.array([
    [
        [2,3,4],
        [6,8,4]
    ],
    
    [
        [1,8,4],
        [6,9,2]
    ]
])

print(d[1,0,2])
print(d[0][1][0])

4
6


In [90]:
# You can pass a list for indexing
print(d[[1],1,[0,1,2]])

[6 9 2]


Negative Indexing

In [36]:
print(d[-1,-1,-1])

2


In [35]:
print(d[:,-1,:])

[[6 8 4]
 [6 9 2]]


## Slicing Arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [45]:
import numpy as np
d = np.array([
    [
        [2,3,4],
        [6,8,4]
    ],
    
    [
        [1,8,4],
        [6,9,2]
    ]
])

In [52]:
print(d[1,:,0:2])

[[1 8]
 [6 9]]


In [53]:
print(d[1,:,0:2:2])

[[1]
 [6]]


In [55]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[:,-2:])

[[ 4  5]
 [ 9 10]]


##### Modifying the Element in an Array

In [43]:
import numpy as np
a = np.array([[1.0, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a)
a[1,-1] = np.NaN

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [44]:
print(a)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. nan]]


You can change multiple element in an array but you have to pass an array with the same shape as the array you want to change.

In [38]:
import numpy as np
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr1[:,-2:])
arr1[:,-2:] = [[5,6],[1,2]]
print(arr1)

[[ 4  5]
 [ 9 10]]
[[1 2 3 5 6]
 [6 7 8 1 2]]


### Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [58]:
# Checking the data type
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr.dtype)

int32


In [59]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


#### Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [63]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype="f")
print(arr)
print(arr.dtype)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
float32


#### Shape of an Array
The shape of an array is the number of elements in each dimension.

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [67]:
import numpy as np

f = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f.shape)

(2, 4)


### Array Reshaping
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

##### Reshaping from 1-D to 2-D

In [93]:
import numpy as np
dd = np.arange(1,13)
print(dd)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [98]:
newdd = dd.reshape((3,4), order="f")
# "F" style arranges from the outer dimension of the array
print(newdd)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


##### Reshape From 1-D to 3-D

In [99]:
import numpy as np
dd = np.arange(1,13)
print(dd)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [102]:
ss = dd.reshape((2,3,2), order="F")
print(ss)

[[[ 1  7]
  [ 3  9]
  [ 5 11]]

 [[ 2  8]
  [ 4 10]
  [ 6 12]]]


##### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [99]:
import numpy as np
dd = np.arange(1,13)
print(dd)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [109]:
ss = dd.reshape((2,2,-1), order="F")
print(ss)

[[[ 1  5  9]
  [ 3  7 11]]

 [[ 2  6 10]
  [ 4  8 12]]]


##### Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [111]:
ss = np.array([[
                    [ 1,  5,  9],
                    [ 3,  7, 11]],
                [
                    [ 2,  6, 10],
                    [ 4,  8, 12]]])

In [114]:
ff = ss.reshape((-1), order="F")
print(ff)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

In [118]:
# We can also use the flatten function
# Returns a copy of the array collapsed into one dimension
dd = ss.flatten(order="A")
print(dd)

[ 1  5  9  3  7 11  2  6 10  4  8 12]


In [121]:
# ravel function
# Return a flattened array.
gg = ss.ravel(order="F")
print(gg)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [129]:
# help(np.flip)
# flip(m, axis=None)
# Reverse the order of elements in an array along the given axis.
# The shape of the array is preserved, but the elements are reordered.
ss = np.array([[
                    [ 1,  5,  9],
                    [ 3,  7, 11]],
                [
                    [ 2,  6, 10],
                    [ 4,  8, 12]]])
zz = np.flip(ss, axis=(0,1,2))
print(zz)

[[[12  8  4]
  [10  6  2]]

 [[11  7  3]
  [ 9  5  1]]]


### Copy vs View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [136]:
# Make a copy, change the original array, and display both arrays:
import numpy as np

aa = np.arange(1,6)
bb = aa.copy()
aa[0] = 57

print(aa)
print(bb)

[57  2  3  4  5]
[1 2 3 4 5]


In [ ]:
np.copyto

In [138]:
# Make a view, change the original array, and display both arrays:
import numpy as np

aa = np.arange(1,6)
bb = aa.view()
aa[0] = 57

print(aa)
print(bb)

[57  2  3  4  5]
[57  2  3  4  5]


In [144]:
# USING THE COPYTO FUNCTION

ee =np.empty(5)
np.copyto(ee, aa, casting="same_kind")
print(ee)

[57.  2.  3.  4.  5.]


##### Checking if Array owns it's Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [145]:
import numpy as np

aa = np.arange(1,6)
bb = aa.view()
cc = aa.copy()

print(bb.base)
print(cc.base)


[1 2 3 4 5]
None


### Array Iterating

### Joining Array
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [154]:
import numpy as np
a1 = np.arange(1,4)
a2 = np.arange(4,7)

print(a1)
print(a2)
print("")

a3 = np.concatenate((a1,a2))
print(a3)

[1 2 3]
[4 5 6]

[1 2 3 4 5 6]


In [174]:
# JOINING 2-D ARRAYS ALONG ROWS
# ROWS BECOME ONE

import numpy as np
a1 = np.arange(1,5).reshape((2,2))
a2 = np.arange(4,8).reshape((2,2))

print(a1)
print(a2)
print("")

a3 = np.concatenate((a1,a2), axis=1)
print(a3)

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]

[[1 2 4 5]
 [3 4 6 7]]


##### Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the concatenate() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [172]:
import numpy as np
a1 = np.arange(1,4)
a2 = np.arange(4,7)

print(a1)
print(a2)
print("")

a3 = np.stack((a1,a2), axis=1)
print(a3)

[1 2 3]
[4 5 6]

[[1 4]
 [2 5]
 [3 6]]


In [170]:
# hstack()

import numpy as np
a1 = np.arange(1,4).reshape(-1)
a2 = np.arange(4,7).reshape(-1)

print(a1)
print(a2)
print("")

aaa = np.hstack((a1,a2))
print(aaa)

[1 2 3]
[4 5 6]

[1 2 3 4 5 6]


In [179]:
# vstack()

import numpy as np
a1 = np.arange(1,4)
a2 = np.arange(4,7)

print(a1)
print(a2)
print("")

aaa = np.vstack((a1,a2))
print(aaa)


[1 2 3]
[4 5 6]

[[1 2 3]
 [4 5 6]]


In [181]:
# column_stack()

import numpy as np
a1 = np.arange(1,4)
a2 = np.arange(4,7)

print(a1)
print(a2)
print("")

aaa = np.column_stack((a1,a2))
print(aaa)


[1 2 3]
[4 5 6]

[[1 4]
 [2 5]
 [3 6]]


In [182]:
# Stacking along Height (depth)

import numpy as np
a1 = np.arange(1,4)
a2 = np.arange(4,7)

print(a1)
print(a2)
print("")

aaa = np.dstack((a1,a2))
print(aaa)


[1 2 3]
[4 5 6]

[[[1 4]
  [2 5]
  [3 6]]]


##### Splitting Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use *array_split()* for splitting arrays, we pass it the array we want to split and the number of splits.

In [193]:
# Syntax: array_split(ary, indices_or_sections, axis=0)
# Split an array into multiple sub-arrays.
# Splitting the array in 3 parts
a = np.arange(1,7)
aa = np.array_split(a,2)
print(aa)

[array([1, 2, 3]), array([4, 5, 6])]


If the array has less elements than required, it will adjust from the end accordingly.

In [190]:
# Splitting the array in 3 parts
a = np.arange(1,7)
aa = np.array_split(a,5)
print(aa)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

In [195]:
# Using the split method
a = np.arange(1,7)
aa = np.split(a,3)
print(aa)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [198]:
# Using the split method
a = np.arange(1,7)
aa = np.split(a,4)
print(aa)

[array([1, 2, 3]), array([4, 5, 6])]


##### Splitting 2-D Arrays
Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

In [209]:
import numpy as np
a = np.arange(1,13).reshape(6,-1)
print(a)

aa = np.array_split(a, 3)
print(aa)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [210]:
import numpy as np
a = np.arange(1,13).reshape(6,-1)
print(a)

aa = np.array_split(a, 3, axis=1)
print(aa)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


In [213]:
# Using the vsplit()
import numpy as np
a = np.arange(1,13).reshape(6,-1)
print(a)
print("")

aa = np.vsplit(a, 3)
print(aa)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [217]:
# Using the hsplit()
import numpy as np
a = np.arange(1,13).reshape(6,-1)
print(a)
print("")

aa = np.hsplit(a,2)
print(aa)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


### Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [35]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(a > 3)

print(x)

(array([3, 4, 5, 6], dtype=int64),)


The returns a tuple that contains an array of indices that match with the search criteria.

We can use this to pull out the actual result of the search.

In [36]:
print(a[x])

[4 5 4 4]


In [38]:
# Example
# Find the indexes where the values are odd:

import numpy as np

b = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

print(b[x])

(array([0, 2, 4, 6], dtype=int64),)
[1 3 5 7]


##### Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [41]:
# Working with unsorted data
import numpy as np
a = np.array([6, 7, 4, 1, 8, 9])

x = np.searchsorted(a, 7)

print(x)

4


In [43]:
# Working with sorted data
import numpy as np
a = np.array([4, 5, 8, 10, 12])
x = np.searchsorted(a, 7)
print(x)

2


##### Search From the Right Side
By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [44]:
import numpy as np

a = np.array([6, 7, 8, 9])

x = np.searchsorted(a, 7, side='right')

print(x)

2


##### Multiple Values
To search for more than one value, use an array with the specified values

In [47]:
import numpy as np
a = np.array([1, 3, 7, 10])
x = np.searchsorted(a, [2,6,5,9])
print(x)

[1 2 2 3]


### Sorting Arrays
Sorting means putting elements in a ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [50]:
# Example
import numpy as np
a = np.array([3, 5, 6, 12, 9, 1])

sort = np.sort(a)
print(sort)

[ 1  3  5  6  9 12]


You can also sort arrays of strings, or any other data type:

In [54]:
fruits = np.array(["Mango", 'Orange', 'Banana', 'Apple', 'Guava'])
a = np.sort(fruits, kind="mergesort")
print(a)

['Apple' 'Banana' 'Guava' 'Mango' 'Orange']


In [52]:
# Sorting a boolean array:
a = np.array([True, False, True, False, False])
x = np.sort(a)
print(x)

[False False False  True  True]


##### Sorting a 2-D Array
If you use the sort() method on a 2-D array, both arrays will be sorted:

In [59]:
import numpy as np
print(arr)
print("")
arr = np.array([[3, 2, 4], [5, 0, 1], [2, 9, 6]])
print(np.sort(arr))

[[3 2 4]
 [5 0 1]
 [2 9 6]]

[[2 3 4]
 [0 1 5]
 [2 6 9]]


In [57]:
# Specifying the axis
import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1], [2, 9, 6]])
print(np.sort(arr, axis=0))

[[2 0 1]
 [3 2 4]
 [5 9 6]]


Sorting Multi-dimension arrays

In [61]:
import numpy as np
a = np.array([
    [
        [3,7,2,9],
        [6,2,9,12],
        [5,2,19,12]
    ],
    
    [
        [4,9,2,10],
        [-2,7,-12, 4],
        [5,15,-4,7]
    ]
])

print(a)

[[[  3   7   2   9]
  [  6   2   9  12]
  [  5   2  19  12]]

 [[  4   9   2  10]
  [ -2   7 -12   4]
  [  5  15  -4   7]]]


In [62]:
print(np.sort(a, axis=2))

[[[  2   3   7   9]
  [  2   6   9  12]
  [  2   5  12  19]]

 [[  2   4   9  10]
  [-12  -2   4   7]
  [ -4   5   7  15]]]


In [67]:
print(np.sort(a, axis=1))

[[[  3   2   2   9]
  [  5   2   9  12]
  [  6   7  19  12]]

 [[ -2   7 -12   4]
  [  4   9  -4   7]
  [  5  15   2  10]]]


In [66]:
print(np.sort(a, axis=0))
# Depth wise sorting

[[[  3   7   2   9]
  [ -2   2 -12   4]
  [  5   2  -4   7]]

 [[  4   9   2  10]
  [  6   7   9  12]
  [  5  15  19  12]]]


### Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [219]:
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x and y

In [10]:
import numpy as np

x = np.array([1, 2, 3, 4])
y = np.array([4, 5, 6, 7])


#z = np.add(x, y)
z = x ** y

print(z)

[    1    32   729 16384]


In [13]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=0)

print(newarr)

[ 5 12 21 32]


In [23]:
import numpy as np

# Create a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [45,76,34]])

# Check if any element in the 2D array is even
result = np.any(arr_2d % 2 == 0, axis=0)

# Print the result
print(result)

[ True  True  True]
